repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --config=blueprint/python/pyproject.toml]
        files: ^blueprint/python/
      - id: ruff-format
        args: [--config=blueprint/python/pyproject.toml]
        files: ^blueprint/python/
        
